### ISSUE TITLE
CT there already was a PhetioElementTreeNode with the same phetioID in the tree

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#103]
```
natural-selection : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591840967654/studio/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591840967654%22%2C%22timestamp%22%3A1591842942622%7D
Uncaught Error: There already was a PhetioElementTreeNode with the same phetioID in the tree: naturalSelection.labScreen.view.environmentNode.bunnyNodeCollection.bunnyNodeGroup.bunnyNode_1
Error: There already was a PhetioElementTreeNode with the same phetioID in the tree: naturalSelection.labScreen.view.environmentNode.bunnyNodeCollection.bunnyNodeGroup.bunnyNode_1
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591840967654/phet-io-wrappers/common/js/assert.js:32:13)
at Function.insertPhetioElementIntoTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591840967654/studio/js/PhetioElementTreeNode.js:94:19)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591840967654/studio/js/Studio.js:275:43)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591840967654/studio/js/main.js:40:26)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591840967654/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591840967654/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/10/2020, 8:02:47 PM
```

**Comment by KatieWoe** [comment]
Also in concentration and beer's law.

**Comment by pixelzoom** [comment]
This is a general Studio problem that was supposedly fixed in https://github.com/phetsims/studio/issues/140.  I'm going to close this issue, and reopen that issue.
