### ISSUE TITLE
CT: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#118]
Broken out from https://github.com/phetsims/natural-selection/issues/117:

```
natural-selection : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1594253492079%22%2C%22timestamp%22%3A1594254809872%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at VBox.onTransformChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/scenery/js/nodes/Node.js:2462:30)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/axon/js/TinyEmitter.js:69:53)
at Transform3.invalidate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/dot/js/Transform3.js:107:24)
at Transform3.prependTranslation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/dot/js/Transform3.js:145:10)
at VBox.prependTranslation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/scenery/js/nodes/Node.js:2408:21)
at VBox.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/scenery/js/nodes/Node.js:2072:14)
at VBox.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/scenery/js/nodes/Node.js:2083:12)
at VBox.setCenter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/scenery/js/nodes/Node.js:2956:12)
at VBox.set center [as center] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/scenery/js/nodes/Node.js:2961:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/natural-selection/js/common/view/proportions/ProportionsGraphNode.js:167:22
id: Bayes Chrome
Snapshot from 7/8/2020, 6:11:32 PM
```

**Comment by pixelzoom** [comment]
Below is the offending code in ProportionsGraphNode.js.  Setting `center` causes bounds to change, so this is an infinite loop. This code has existed since 6/10/2020.  No idea why it suddenly became a problem.  The solution is to wrap content in another Node.

```js
    // Center on the background. Columns may be removed via PhET-iO, so observe bounds. unlink is not necessary.
    content.boundsProperty.link( () => {
      content.center = backgroundNode.center;
    } );
```

**Comment by pixelzoom** [comment]
Reproduced at startup with `?brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000`.

**Comment by pixelzoom** [comment]
Fixed in the above commit. I'll leave this open until CT is happy.

**Comment by pixelzoom** [comment]
All clear in CT, closing.
