### ISSUE TITLE
CT tried to removeListener on something that wasn't a listener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#126]
```
natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1594375074518%22%2C%22timestamp%22%3A1594378813381%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/assert/js/assert.js:22:13)
at TinyEmitter.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/TinyEmitter.js:107:7)
at Emitter.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:86:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/js/common/view/environment/EnvironmentNode.js:125:30
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:58:19)
at Wolf.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/js/common/model/Wolf.js:72:26)
at Wolf.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/tandem/js/PhetioObject.js:199:20)
id: Bayes Chrome
Snapshot from 7/10/2020, 3:57:54 AM

----------------------------------

natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1594375074518%22%2C%22timestamp%22%3A1594387247311%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/assert/js/assert.js:22:13)
at TinyEmitter.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/TinyEmitter.js:107:7)
at Emitter.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:86:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/js/common/view/environment/EnvironmentNode.js:125:30
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:58:19)
at Wolf.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/js/common/model/Wolf.js:72:26)
at Wolf.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/tandem/js/PhetioObject.js:199:20)
id: Bayes Chrome
Snapshot from 7/10/2020, 3:57:54 AM

----------------------------------

natural-selection : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/studio/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594375074518%22%2C%22timestamp%22%3A1594387129968%7D
Uncaught Error: Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/assert/js/assert.js:22:13)
at TinyEmitter.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/TinyEmitter.js:107:7)
at Emitter.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:86:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/js/common/view/environment/EnvironmentNode.js:125:30
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:58:19)
at Wolf.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/natural-selection/js/common/model/Wolf.js:72:26)
at Wolf.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/tandem/js/PhetioObject.js:199:20)
id: Bayes Chrome
Snapshot from 7/10/2020, 3:57:54 AM
```

**Comment by pixelzoom** [comment]
Fixed in the above commit. I'll leave this open until CT confirms.

**Comment by pixelzoom** [comment]
Looks good in CT, closing.
