### ISSUE TITLE
CT: sprite instance not found for selected bunny

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#133]
Related to reimplementation using sprites in #128.

```
natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594907045052%22%2C%22timestamp%22%3A1594912247467%7D
Uncaught Error: Assertion failed: sprite instance not found for selected bunny
Error: Assertion failed: sprite instance not found for selected bunny
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:341:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/axon/js/PropertyStateHandler.js:263:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/axon/js/PropertyStateHandler.js:197:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/axon/js/PropertyStateHandler.js:71:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594907045052/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/16/2020, 7:44:05 AM
```

**Comment by KatieWoe** [comment]
Related errors?:
```
natural-selection : fuzz : unbuilt : query-parameters
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594947949889%7D&brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Query: brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Uncaught Error: Assertion failed: expected selectionRectangleSpriteInstance in spriteInstances
Error: Assertion failed: expected selectionRectangleSpriteInstance in spriteInstances
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:325:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:171:14)
at SelectedBunnyProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:336:10)
at BunnyCollection.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/model/BunnyCollection.js:198:32)
at IntroModel.startOver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/model/NaturalSelectionModel.js:233:26)
at IntroModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/model/NaturalSelectionModel.js:213:10)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : fuzz : unbuilt : query-parameters
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594982674224%7D&brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Query: brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Uncaught Error: Assertion failed: expected selectionRectangleSpriteInstance in spriteInstances
Error: Assertion failed: expected selectionRectangleSpriteInstance in spriteInstances
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:325:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:171:14)
at SelectedBunnyProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:336:10)
at BunnyCollection.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/model/BunnyCollection.js:198:32)
at IntroModel.startOver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/model/NaturalSelectionModel.js:233:26)
at IntroModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/model/NaturalSelectionModel.js:213:10)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594983230473%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: expected selectedBunnySpriteInstance to be in spriteInstances
Error: Assertion failed: expected selectedBunnySpriteInstance to be in spriteInstances
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:379:17)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:206:10)
at EnvironmentNode.updateSprites (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/EnvironmentNode.js:96:18)
at endSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/NaturalSelectionScreenView.js:257:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/NaturalSelectionScreenView.js:265:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Emitter.js:58:19)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594993441117%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: expected selectedBunnySpriteInstance to be in spriteInstances
Error: Assertion failed: expected selectedBunnySpriteInstance to be in spriteInstances
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:379:17)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:206:10)
at EnvironmentNode.updateSprites (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/EnvironmentNode.js:96:18)
at endSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/NaturalSelectionScreenView.js:257:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/NaturalSelectionScreenView.js:265:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Emitter.js:58:19)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594946504144%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/tandem/js/PhetioGroup.js:69:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Emitter.js:58:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io/js/PhetioStateEngine.js:252:26)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io/js/PhetioStateEngine.js:267:10)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io/js/PhetioEngineIO.js:221:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io/js/phetioCommandProcessor.js:270:51)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594958005418%7D
Uncaught Error: Assertion failed: sprite instance not found for selected bunny
Error: Assertion failed: sprite instance not found for selected bunny
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:341:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:263:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:197:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:71:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594970056414%7D
Uncaught Error: Assertion failed: sprite instance not found for selected bunny
Error: Assertion failed: sprite instance not found for selected bunny
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:341:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:263:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:197:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:71:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594982033223%7D
Uncaught Error: Assertion failed: sprite instance not found for selected bunny
Error: Assertion failed: sprite instance not found for selected bunny
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:341:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:263:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:197:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:71:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM

----------------------------------

natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594945122902%22%2C%22timestamp%22%3A1594993731671%7D
Uncaught Error: Assertion failed: sprite instance not found for selected bunny
Error: Assertion failed: sprite instance not found for selected bunny
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:341:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:263:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:197:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/PropertyStateHandler.js:71:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594945122902/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/16/2020, 6:18:42 PM
```

**Comment by pixelzoom** [comment]
#132 and #133 had the same root cause -- incorrect handling of `selectedBunnyProperty`.  Fixed in the above commit.  I'll wait to close until I verify that CT is happy.

**Comment by pixelzoom** [comment]
This one appears to be fixed in CT.  Closing.
