### ISSUE TITLE
Bunnies not getting disposed?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#136]
I ran [dev.70](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.70/phet/natural-selection_en_phet.html?log) until generation 5, at which point I checked Limited Food to stabilize the population. At Generation 12 the bunnies took over the world. I selected a bunny, then another, then clicked reset-all. Now at Generation 0 there is a bunny that appears to still be "selected" in the log, and is present in the environment along with the new initial bunny. Nothing in the console.

![image](https://user-images.githubusercontent.com/7852916/87718860-be866f00-c76f-11ea-9e83-a04954418c6d.png)

natural-selection_en_phet.html?log:81 ====== Generation 12 ======
natural-selection_en_phet.html?log:81 2 bunnies died of old age
natural-selection_en_phet.html?log:81 500 bunnies were born
natural-selection_en_phet.html?log:81 Bunnies have taken over the world.
natural-selection_en_phet.html?log:81 total live bunnies = 750
natural-selection_en_phet.html?log:81 total dead bunnies = 2576
natural-selection_en_phet.html?log:81 selectedBunny=bunny_2836, generation=12, age=0, isAlive=true, , genotype='', father=bunny_2394, mother=bunny_2530
natural-selection_en_phet.html?log:81 selectedBunny=bunny_3016, generation=12, age=0, isAlive=true, , genotype='', father=bunny_1632, mother=bunny_2761
natural-selection_en_phet.html?log:81 ====== Generation 0 ======
natural-selection_en_phet.html?log:81 selectedBunny=null
natural-selection_en_phet.html?log:81 NaturalSelectionModel.initializeGenerationZero
natural-selection_en_phet.html?log:81 creating 1 bunnies with genotype ''
natural-selection_en_phet.html?log:81 selectedBunny=bunny_2836, generation=12, age=0, isAlive=true, , genotype='', father=bunny_2394, mother=bunny_2530
natural-selection_en_phet.html?log:81 selectedBunny=null

**Comment by amanda-phet** [comment]
I'm able to make more bunny ghosts if I click on more while in this paused, bunnies took over the world state (btw, to reproduce, you don't need to use limited food. Just let the bunnies take over the world). However, it's consistently not *every* bunny I previously clicked.

![image](https://user-images.githubusercontent.com/7852916/87719346-7287fa00-c770-11ea-8935-4bcae15c0c88.png)

Here there are 3 ghost bunnies, but I had clicked on 7 before clicking reset-all.

natural-selection_en_phet.html?log:81 ====== Generation 6 ======
natural-selection_en_phet.html?log:81 4 bunnies died of old age
natural-selection_en_phet.html?log:81 952 bunnies were born
natural-selection_en_phet.html?log:81 Bunnies have taken over the world.
natural-selection_en_phet.html?log:81 total live bunnies = 1428
natural-selection_en_phet.html?log:81 total dead bunnies = 6
natural-selection_en_phet.html?log:81 selectedBunny=bunny_1301, generation=6, age=0, isAlive=true, , genotype='', father=bunny_103, mother=bunny_443
natural-selection_en_phet.html?log:81 selectedBunny=bunny_356, generation=5, age=1, isAlive=true, , genotype='', father=bunny_3, mother=bunny_142
natural-selection_en_phet.html?log:81 selectedBunny=bunny_329, generation=5, age=1, isAlive=true, , genotype='', father=bunny_150, mother=bunny_103
natural-selection_en_phet.html?log:81 selectedBunny=bunny_369, generation=5, age=1, isAlive=true, , genotype='', father=bunny_141, mother=bunny_57
natural-selection_en_phet.html?log:81 selectedBunny=bunny_1097, generation=6, age=0, isAlive=true, , genotype='', father=bunny_418, mother=bunny_356
natural-selection_en_phet.html?log:81 selectedBunny=bunny_527, generation=6, age=0, isAlive=true, , genotype='', father=bunny_454, mother=bunny_450
natural-selection_en_phet.html?log:81 selectedBunny=bunny_1316, generation=6, age=0, isAlive=true, , genotype='', father=bunny_330, mother=bunny_48
natural-selection_en_phet.html?log:81 ====== Generation 0 ======
natural-selection_en_phet.html?log:81 selectedBunny=null
natural-selection_en_phet.html?log:81 NaturalSelectionModel.initializeGenerationZero
natural-selection_en_phet.html?log:81 creating 1 bunnies with genotype ''

**Comment by pixelzoom** [comment]
Related to sprites implementation #128.

**Comment by KatieWoe** [comment]
Is this related to this CT error?
```
natural-selection : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595341862058%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: number of bunny sprites 2 is out of sync with number of bunnies 1
Error: Assertion failed: number of bunny sprites 2 is out of sync with number of bunnies 1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:430:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:348:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:179:63
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:171:14)
at SelectedBunnyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:343:32)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

natural-selection : fuzz : unbuilt : query-parameters
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595339688750%7D&brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Query: brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Uncaught Error: Assertion failed: number of bunny sprites 1 is out of sync with number of bunnies 10
Error: Assertion failed: number of bunny sprites 1 is out of sync with number of bunnies 10
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.createBunnySpriteInstance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:230:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:164:56
at Array.forEach (<anonymous>)
at BunnyArray.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/ObservableArray.js:305:25)
at new NaturalSelectionSprites (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:164:33)
at new EnvironmentNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/EnvironmentNode.js:51:21)
at new NaturalSelectionScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/NaturalSelectionScreenView.js:66:29)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/intro/view/IntroScreenView.js:25:5)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340249786%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:430:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:348:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:179:63
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:171:14)
at SelectedBunnyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:343:32)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

natural-selection : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595339718146%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:430:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:348:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:179:63
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:171:14)
at SelectedBunnyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:343:32)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

natural-selection : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/phet-io-wrappers/mirror-inputs/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340171421%7D
Uncaught Error: Uncaught Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:430:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:348:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:179:63
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:171:14)
at SelectedBunnyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:343:32)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595340652976%7D
Uncaught Error: Uncaught Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:430:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:348:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:179:63
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:171:14)
at SelectedBunnyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:343:32)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

natural-selection : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/studio/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595341109569%7D
Uncaught Error: Uncaught Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:430:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:348:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:179:63
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:171:14)
at SelectedBunnyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Property.js:343:32)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM

----------------------------------

natural-selection : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1595339019150%22%2C%22timestamp%22%3A1595342385556%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: number of bunny sprites 2 is out of sync with number of bunnies 1
Error: Assertion failed: number of bunny sprites 2 is out of sync with number of bunnies 1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:461:15)
at NaturalSelectionSprites.createBunnySpriteInstance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:230:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:167:68
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/Emitter.js:58:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/natural-selection/js/common/model/BunnyCollection.js:172:32
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595339019150/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/21/2020, 7:43:39 AM
```

**Comment by pixelzoom** [comment]
Thanks for the report @KatieWoe.  The above errors, the original error reported, and #132 are all related to work done in #128 -- which was a total reimplementation of the "environment" view that should bunnies, wolves, etc.   This was a big, complicated change, and I'm (obviously) still working the bugs out.

**Comment by pixelzoom** [comment]
There was a bug in NaturalSelectionSprites `sort` that took me forever to find, fixed in https://github.com/phetsims/natural-selection/commit/cdc84e8ff63e9bc4ad2747fa8161f19022e4e9ed.   I think that should do it, but will wait for a few CT cycles before closing.

**Comment by pixelzoom** [comment]
CT is happy.  

@amanda-phet please verify in [1.0.0-dev.72](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.72/phet/natural-selection_en_phet.html) or master.

**Comment by amanda-phet** [comment]
Looks like it is fixed!
