### ISSUE TITLE
CT: number of bunny sprites 1 is out of sync with number of bunnies 0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#139]
Related to new sprites implementation.  Note that counts are out of sync for bunnies and wolves, in 2 different tests:

* `fuzz : unbuilt : secondsPerGeneration` -> "number of bunny sprites 1 is out of sync with number of bunnies 0"

* `phet-io-state-fuzz : unbuilt` -> "number of wolf sprites 1 is out of sync with number of wolves 10"

```
natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1595440105379%22%2C%22timestamp%22%3A1595442842165%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: number of bunny sprites 1 is out of sync with number of bunnies 0
Error: Assertion failed: number of bunny sprites 1 is out of sync with number of bunnies 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:477:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:446:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at EnvironmentNode.updateSprites (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/EnvironmentNode.js:96:18)
at endSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/NaturalSelectionScreenView.js:257:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/NaturalSelectionScreenView.js:265:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 7/22/2020, 11:48:25 AM

----------------------------------

natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595440105379%22%2C%22timestamp%22%3A1595441416919%7D
Uncaught Error: Assertion failed: number of wolf sprites 1 is out of sync with number of wolves 10
Error: Assertion failed: number of wolf sprites 1 is out of sync with number of wolves 10
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertWolvesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:488:15)
at NaturalSelectionSprites.createWolfSpriteInstance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:262:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:170:65
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Emitter.js:58:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/model/WolfCollection.js:93:31
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/22/2020, 11:48:25 AM
```

**Comment by pixelzoom** [comment]
I reproduced the first error with `natural-selection_en.html?brand=phet&ea&log&fuzz&secondsPerGeneration=1`.  Here's the log just before the failure:

```
====== Generation 0 ======
NaturalSelectionModel.initializeGenerationZero
creating 1 bunnies with genotype ''
selectedBunny=bunny_0, generation=0, age=0, isAlive=true, , genotype='TT', father=null, mother=null
No bunnies with long teeth were starved because the population is <= 4.
All of the bunnies have died.
total live bunnies = 0
total dead bunnies = 2
Assertion failed: number of bunny sprites 1 is out of sync with number of bunnies 0
```

**Comment by pixelzoom** [comment]
Most recent failure, for current stack trace:

```
natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1595960493090%22%2C%22timestamp%22%3A1595964100122%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: number of bunny sprites 1 is out of sync with number of bunnies 0
Error: Assertion failed: number of bunny sprites 1 is out of sync with number of bunnies 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:495:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:464:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at EnvironmentNode.updateSprites (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/natural-selection/js/common/view/environment/EnvironmentNode.js:96:18)
at endSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/natural-selection/js/common/view/NaturalSelectionScreenView.js:262:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/natural-selection/js/common/view/NaturalSelectionScreenView.js:270:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595960493090/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 7/28/2020, 12:21:33 PM
```

**Comment by pixelzoom** [comment]
Steps to reproduce manually:

1. Start the sim with brand=phet&ea&secondsPerGeneration=1&log
2. Go to Intro screen
3. Select the lone bunny
4. Check the "Wolves" checkbox
5. Press the "Add a Mate" button
6. Wait for assertion failure to occur.

**Comment by pixelzoom** [comment]
There's a bit of an ordering issue here.  When all of the bunnies die or take over the world, there's an explicit call to NaturalSelectionSprites `update`.  This is so that bunnies are not left up in the air, mid hop.   This call occurs before the selected bunny's `diedEmitter` fires, so the sprite for the selected bunny still exists.   We therefore have 1 sprite and 0 bunnies.  

Since the `assertBunniesCount` in this case has served its purposed, the easiest thing to do is remove it -- so that's what I've done.

**Comment by pixelzoom** [comment]
I been unable to reproduce the 2nd assertion failure:

`Error: Assertion failed: number of wolf sprites 1 is out of sync with number of wolves 10`

So I've moved it to https://github.com/phetsims/natural-selection/issues/141.

If the "number of bunny sprites 1 is out of sync with number of bunnies 0" failure is resolved in CT for a few cycles, I'll close this issue.

**Comment by pixelzoom** [comment]
I decided to delete `assertBunniesCount` altogether, done in the above commit.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
