### ISSUE TITLE
CT:  number of wolf sprites 1 is out of sync with number of wolves 10

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#141]
Factored out of https://github.com/phetsims/natural-selection/issues/139, since it seems to be independent:

```
natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595440105379%22%2C%22timestamp%22%3A1595441416919%7D
Uncaught Error: Assertion failed: number of wolf sprites 1 is out of sync with number of wolves 10
Error: Assertion failed: number of wolf sprites 1 is out of sync with number of wolves 10
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertWolvesCount (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:488:15)
at NaturalSelectionSprites.createWolfSpriteInstance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:262:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:170:65
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/Emitter.js:58:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/natural-selection/js/common/model/WolfCollection.js:93:31
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595440105379/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 7/22/2020, 11:48:25 AM
```

**Comment by pixelzoom** [comment]
Similar to `assertBunniesCount` in #139, I decided to delete `assertWolvesCount`.  It has outlived its usefulness.

If CT is happy after a few cycles, I'll close this issue.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
