### ISSUE TITLE
CT: selectedBunnySpriteInstance missing from spriteInstances

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#149]
```
natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596409518749%22%2C%22timestamp%22%3A1596444928743%7D
Uncaught Error: Assertion failed: selectedBunnySpriteInstance missing from spriteInstances
Error: Assertion failed: selectedBunnySpriteInstance missing from spriteInstances
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/assert/js/assert.js:22:13)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:464:17)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at disposeBunnySpriteInstance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:244:14)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/axon/js/Emitter.js:58:19)
at Bunny.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/natural-selection/js/common/model/Bunny.js:182:26)
at Bunny.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596409518749/tandem/js/PhetioObject.js:199:20)
id: Bayes Chrome
Snapshot from 8/2/2020, 5:05:18 PM
```

**Comment by pixelzoom** [comment]
Note that this is different from #138, because it's occurring in `NaturalSelectionSprites.sort`.

**Comment by pixelzoom** [comment]
I'm guessing that the selected bunny dies, its sprite gets removed by disposeBunnySpriteInstance. But `this.selectedBunnySpriteInstance` is still pointing to the selected bunny's sprite. So sort thinks that there's still a selection and tries to remove it again for sorting.

**Comment by pixelzoom** [comment]
Two things here:

(1) Removing something doesn't require calling sort, and that was being done in a number of places. Corrected in the above commit.

(2) The callback when a bunny dies or is disposed should be responsible for clearing the selection, if the bunny is the selected bunny.  Corrected in the above commit.

Let's see how CT feels about this.

**Comment by pixelzoom** [comment]
CT has been happy for many cycles.

Since this issues has been specific to PhET-iO tests, it will not be patched into the 1.0 (prototype) branch.

Closing.

**Comment by pixelzoom** [comment]
Reopening.  I decided to patch this into the 1.0 branch, in case more changes are needed to NaturalSelectionSprites.js in a subsequent RC.   

Ready for verification in the next RC.  There's nothing specific to test, just be on the lookout for anything odd with sprites in the environment view.

**Comment by pixelzoom** [comment]
Since the next 1.0 RC is going to be a merge from master, closing this issue.
