### ISSUE TITLE
CT designed api changes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#308]
```
natural-selection : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643950008365%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:336:23)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

natural-selection : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643962760816%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

phetioEngine.phetioElementMouseOverProperty.phetioTypeName changed from PropertyIO<NullableIO<StringIO>> to PropertyIO<StringIO>

phetioEngine.phetioElementMouseOverProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":null}
actual:
{"value":"{\"phetioID\":null,\"altKey\":false,\"ctrlKey\":false}","validValues":null,"units":null}

at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/phet-io/js/phetioEngine.js:336:23)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM
```

**Comment by pixelzoom** [comment]
According to @zepumph, this was caused by https://github.com/phetsims/phet-io/commit/2f55312540f657d5c893a0dc6d163d50907d4e8c#diff-32eb810879d5cf8fc29cbccd53bc20fa8713eea8ef401dd531554850b93b5f6cR179 for https://github.com/phetsims/studio/issues/243, and a failure to regenerate the API file for this sim.  CT currently shows the problem has been corrected. If it comes up again, please report in https://github.com/phetsims/studio/issues/243.
