### ISSUE TITLE
CT invalid hopDelta

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#52]
```
natural-selection : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: invalid hopDelta
Error: Assertion failed: invalid hopDelta
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/assert/js/assert.js:22:13)
    at Bunny.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/natural-selection/js/common/model/Bunny.js:336:15)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/natural-selection/js/common/model/BunnyIO.js:52:11)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io/js/PhetioStateEngine.js:247:22)
    at setStateOnce (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io/js/PhetioStateEngine.js:176:33)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io/js/PhetioStateEngine.js:182:7)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io/js/PhetioEngineIO.js:201:43)
id: Bayes Chrome
Approximately 4/10/2020, 3:14:57 AM
natural-selection : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io-wrappers/phet-io-wrappers-tests.html?sim=natural-selection&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 4/10/2020, 3:14:57 AM
natural-selection : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1586510097806/phet-io-wrappers/phet-io-wrappers-tests.html?sim=natural-selection
9 out of 9 tests passed. 0 failed.

Approximately 4/10/2020, 3:14:57 AM
```

**Comment by pixelzoom** [comment]
Fixed in the above commit.  This was a problem with type validation during phet-io deserialization.  I generalized `validatedInstance` for all serializable classes, so that the same validation is performed on construction and on deserialization.

I'll leave this open for a couple of CT cycles before closing.

**Comment by pixelzoom** [comment]
Passing CT. Closing.
