### ISSUE TITLE
CT: Cannot es5-set values directly to a DerivedProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/natural-selection#78]
```
natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589501491004%22%2C%22timestamp%22%3A1589505155409%7D
Uncaught Error: Cannot es5-set values directly to a DerivedProperty, tried to set: [Range (min:0 max:0)]
Error: Cannot es5-set values directly to a DerivedProperty, tried to set: [Range (min:0 max:0)]
at DerivedProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/DerivedProperty.js:118:33)
at Function.setValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/NumberPropertyIO.js:84:42)
at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io/js/PhetioStateEngine.js:517:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io/js/PhetioStateEngine.js:442:14
at Array.forEach (<anonymous>)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io/js/PhetioStateEngine.js:425:22)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io/js/PhetioStateEngine.js:200:31)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io/js/PhetioEngineIO.js:221:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io/js/phetioCommandProcessor.js:267:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/phet-io/js/phetioCommandProcessor.js:160:36
id: Bayes Chrome
Snapshot from 5/14/2020, 4:11:31 PM
```

**Comment by zepumph** [comment]
@pixelzoom, this looks like a bug in how NumberPropertyIO.setValue handles setting its rangeProperty. It tried to set it even when it was  a deriedProperty. NS seemed to be the first test case for this. Please review my commit above.

**Comment by pixelzoom** [comment]
This must've started after I applied the patch in https://github.com/phetsims/axon/issues/289.  I've reopened that issue, and will review these 2 issues together.

**Comment by pixelzoom** [comment]
As I feared, this fix and the patch in phetsims/axon#289 seem to have resulted in this CT error:

```
natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1589501491004%22%2C%22timestamp%22%3A1589506127565%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: value failed isValidValue: 1
Error: Assertion failed: value failed isValidValue: 1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/assert/js/assert.js:22:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/ValidatorDef.js:298:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/validate.js:27:18)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/NumberProperty.js:95:11)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/NumberProperty.js:111:43)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/Property.js:170:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/DerivedProperty.js:71:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589501491004/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 5/14/2020, 6:11:31 PM
```

So I'm back to where I started with phetsims/axon#289, which is not being able to use `DerivedProperty` for my NumberProperty's range (`generationRangeProperty`).

**Comment by zepumph** [comment]
It is possible that we can now use Property state order dependency calls to solve this. I'll take a look.

**Comment by zepumph** [comment]
I can't reproduce the error in https://github.com/phetsims/natural-selection/issues/78#issuecomment-628994751.

**Comment by pixelzoom** [comment]
I also can't produce the error in https://github.com/phetsims/natural-selection/issues/78#issuecomment-628994751, but it's still occurring in CT (though not every cycle).

**Comment by pixelzoom** [comment]
Steps to reproduce:

1. Run sim standalone with `?secondsPerGeneration=1`.
2. Go to Lab screen
3. Select "Proportions" radio button
4. Press "Add a Mate" button, let it run until bunnies have taken over the work, close dialog.
5. Change "Generation" spinner (below Proportions graph) to a value other than zero.
6. Press "Start Over" or "Reset All" button.

**Comment by pixelzoom** [comment]
Discuss with @zepumph @samreid @chrisklus via Zoom.   

This is indeed back to the original problem that I encountered. That is, in ProportionsModel.js, `generationRangeProperty` is being reset before `generationProperty`, which causes a validation error in NumberProperty.   The options to address this are:

(1) Reimplement `generationRangeProperty ` as a Property, use setValueAndRange and resetValueAndRange when changing `generationProperty`.

(2) Reset the dependencies for `generationRangeProperty` before resetting ProportionsModel.

The PhET-iO team recommended (2), which I've done in the above commit.

I'll monitor CT and close if this looks OK after a few cycles.

**Comment by zepumph** [comment]
@samreid, @chrisklus and I discussed setting NumberProperty and its rangeProperty for PhET-iO state a bit more, and we were able to remove some of the "work arounds" in NumberProperty and NumberPropertyIO by adding an order dependency. This cleaned up and simplified code. 

This shouldn't effect any sims, but we will keep an eye on CT.

**Comment by pixelzoom** [comment]
No problems after 3 cycles of CT, so closing.

**Comment by zepumph** [comment]
After https://github.com/phetsims/axon/commit/b222e1a4b25ad63203bfe1fdecdb3c3b94f900c6, it isn't expected the NumberProperty will be able to set an uninstrumented rangeProperty's state on its own, so I updated the test in `phet-io-test-sim` too.
