### ISSUE TITLE
CT: counts out of sync

### ISSUE THREAD

**Issue by zepumph** [phetsims/natural-selection#81]
This is occurring because of https://github.com/phetsims/phet-io/issues/1661. There is an assertion in BunnyArray that is firing immediately, and checking against deferred Properties. This will be broken in the state engine until that issue is sorted out.

Tagging @pixelzoom so he realized what is going on.
```
Uncaught Error: Assertion failed: counts out of sync
Error: Assertion failed: counts out of sync
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/natural-selection/js/common/model/BunnyArray.js:37:17
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/axon/js/Emitter.js:58:19)
at BunnyArray._fireItemAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/axon/js/ObservableArray.js:136:27)
at BunnyArray.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/axon/js/ObservableArray.js:221:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/natural-selection/js/common/model/BunnyCollection.js:87:26
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590096316283/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 5/21/2020, 1:25:16 PM
```

**Comment by pixelzoom** [comment]
State has gotten more complicated than I can comprehend, and it feels like a moving target. So I'm going to ignore this for awhile, and assume that it will get worked out in the state engine.

**Comment by zepumph** [comment]
>State has gotten more complicated than I can comprehend

Hey me too! We are working on this part too.

**Comment by pixelzoom** [comment]
@zepumph The ObservableArrays where this is an issue both have `phetioState: false`, because they are populated as the BunnyGroup is restored.  So will addressing  phetsims/phet-io#1661 resolve this issue?

**Comment by pixelzoom** [comment]
Maybe I need to set `phetioState: false` for all of the Properties in BunnyCount.js, since they should also be updated as BunnyGroup is restored?

**Comment by pixelzoom** [comment]
> So I'm going to ignore this for awhile, and assume that it will get worked out in the state engine.

OK, I lied.  I couldn't stand this failing continuously.  And it fails when the sim starts, so makes it impossible to test other things in the State wrapper. 

The above commit seems to resolve the issue.  All of the NumberProperty instances (counts) in BunnyCount are updated as Bunny instances are created/die/disposed.  So I made all of these NumberProperty instances `phetioState: false`.

@zepumph does this seem like the correct fix for this?

**Comment by zepumph** [comment]
That is a very elegant solution. It does seem like data downstream of a PhetioGroup doesn't need to be stateful. I will keep pondering about that pattern. 

In your case, there is logic built into the BunnyCollection to update the ObservableArrays based on then PhetioGroup is populated. This works because the Bunny itself holds the data about what list (dead or alive) it goes into, so once it is reserliazed, it is also pushed to a list. This isn't always the case, but I'm glad it works well in your case!

For the NumberProperties, I do think marking `phetioState:false` is best.

**Comment by pixelzoom** [comment]
Rats, this problem has returned, CT report below.  I'm not certain if it's still related to BunnyGroup, or the new WolfGroup that was added earlier today.  But I see the same problem at 12:05am this morning, long before WolfGroup was added. 

```
natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1590599772238%22%2C%22timestamp%22%3A1590603649651%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/tandem/js/PhetioGroup.js:69:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/axon/js/Emitter.js:58:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/phet-io/js/PhetioStateEngine.js:219:26)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/phet-io/js/PhetioEngineIO.js:221:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/phet-io/js/phetioCommandProcessor.js:267:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590599772238/phet-io/js/phetioCommandProcessor.js:160:36
id: Bayes Chrome
Snapshot from 5/27/2020, 11:16:12 AM
```
