### ISSUE TITLE
CT: index out of bounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#83]
```
natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1590125058074%22%2C%22timestamp%22%3A1590142487075%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: index out of bounds: 0
Error: Assertion failed: index out of bounds: 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/assert/js/assert.js:22:13)
at ObservableArray.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/ObservableArray.js:274:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/natural-selection/js/common/model/ProportionsModel.js:131:58
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/Property.js:170:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/DerivedProperty.js:71:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590125058074/axon/js/Property.js:270:25)
id: Bayes Chrome
Snapshot from 5/21/2020, 11:24:18 PM
```

@pixelzoom edit: Deleted the Errors that are being tracked in #81.

**Comment by pixelzoom** [comment]
Thanks. This is a known problem, related to #57, work-in-progress for the Proportions graph.  It may stay broken for awhile.

**Comment by pixelzoom** [comment]
This should be fixed now.  I'll close after CT confirms.

**Comment by pixelzoom** [comment]
This has been clean in CT for 2 cycles.  Closing.
