### ISSUE TITLE
CT: index out of bounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#84]
Known problem, related to #57, working in progress on the Proportions graph. 

```
natural-selection : fuzz : unbuilt : secondsPerGeneration
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22secondsPerGeneration%22%5D%2C%22snapshotName%22%3A%22snapshot-1590131089190%22%2C%22timestamp%22%3A1590134385812%7D&brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Query: brand=phet&ea&fuzz&memoryLimit=1000&secondsPerGeneration=1
Uncaught Error: Assertion failed: index out of bounds: 0
Error: Assertion failed: index out of bounds: 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/assert/js/assert.js:22:13)
at ObservableArray.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/ObservableArray.js:274:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/natural-selection/js/common/model/ProportionsModel.js:131:58
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/Property.js:170:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/DerivedProperty.js:71:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590131089190/axon/js/Property.js:270:25)
id: Bayes Chrome
Snapshot from 5/22/2020, 1:04:49 AM
```

**Comment by pixelzoom** [comment]
Duplicate of #83.
