### ISSUE TITLE
CT There already was a PhetioElementTreeNode with the same phetioID in the tree

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#99]
```
natural-selection : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591573219042%22%2C%22timestamp%22%3A1591577060594%7D
Uncaught Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/assert.js:32:13)
at Function.insertPhetioElementIntoTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/PhetioElementTreeNode.js:94:19)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/Studio.js:274:43)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/main.js:40:26)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 5:40:19 PM

----------------------------------

natural-selection : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591573219042%22%2C%22timestamp%22%3A1591591001658%7D
Uncaught Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/assert.js:32:13)
at Function.insertPhetioElementIntoTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/PhetioElementTreeNode.js:94:19)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/Studio.js:274:43)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/main.js:40:26)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 5:40:19 PM

----------------------------------

natural-selection : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591573219042%22%2C%22timestamp%22%3A1591601021371%7D
Uncaught Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/assert.js:32:13)
at Function.insertPhetioElementIntoTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/PhetioElementTreeNode.js:94:19)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/Studio.js:274:43)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/main.js:40:26)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 5:40:19 PM

----------------------------------

natural-selection : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591573219042%22%2C%22timestamp%22%3A1591615291990%7D
Uncaught Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
Error: There already was a PhetioElementTreeNode with the same phetioID in the tree.
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/assert.js:32:13)
at Function.insertPhetioElementIntoTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/PhetioElementTreeNode.js:94:19)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/Studio.js:274:43)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/studio/js/main.js:40:26)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:469:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591573219042/phet-io-wrappers/common/js/Client.js:342:24)
id: Bayes Chrome
Snapshot from 6/7/2020, 5:40:19 PM
```

**Comment by zepumph** [comment]
Likely a result of work done in phetsims/studio#30. I'll take a look.

**Comment by pixelzoom** [comment]
This type of error has usually been caused when I've forgotten to dispose of some dynamic element, or made a copy-paste error and used the same tandem name for 2 static elements.

It would be super helpful if the message include the duplicated phetioID.

**Comment by pixelzoom** [comment]
If I add the phetioID to the error message in PhetioElementTreeNode.js:

```js
        assert && assert( !( previousTreeNode instanceof PhetioElementTreeNode ),
          `There already was a PhetioElementTreeNode with the same phetioID in the tree: ${phetioElementTreeNode.phetioID}` );
```

The message identifies this phetioID:

> There already was a PhetioElementTreeNode with the same phetioID in the tree: naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_0

**Comment by zepumph** [comment]
>No idea why this started happening

Large changes to the studio tree creation logic occurred at the end of last week. I think we should start with assuming it has nothing to do with Natural Selection.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/studio/issues/30, @chrisklus, @samreid and I worked to convert studio tree code from a "tear-down and rebuild" strategy each time a new element is removed/added to instead a tree-mutation strategy. Details are in that issue. 

This issue is down stream of us not accurately handling the case where an element is added and removed in the same frame, such that at least three separate messages are sent from the sim to studio: add bunny_0, dispose bunny_0, add bunny_0. 

It seems like the thing to fix here is the incomplete logic here in STUDIO/main.js:

```js

  /**
   * On phet-io element removed function that is passed into the phet-io framework. It is called each time a phet-io
   * element is disposed/removed from the sim.
   * @param {String} phetioID
   */
  const phetioElementRemoved = phetioID => {
    if ( window.phetio.studio.phetioElements.hasOwnProperty( phetioID ) ) {
      window.phetio.studio.onPhetioElementRemoved( phetioID );
    }
    else {
      // A PhET-iO element was added and removed faster than Studio could have received the message and added the element.
    }
  };
```

Now that we mutate the tree, we need to be more intelligent than the above snippet.


Through my investigation, there was some chance that both "added" messages were sent before studio got the "removed" event in between the two. If that is the case, then it is likely that this issue will increase the priority of https://github.com/phetsims/phet-io/issues/1654.


I'm sorry to say that I don't have more time to devote to this until Wednesday, and it will require a deeper dive. It isn't enough to remove the assertion so that it doesn't block studio fuzzing, as it is upstream of an actual logic error.

**Comment by zepumph** [comment]
>Now that we mutate the tree, we need to be more intelligent than the above snippet.



Another way to say this is to recognize that we are now using a scalpel instead of a sledge hammer for the tree, and that has exposed underlying order-of-operation issues that we have not cared about up until this point.

**Comment by pixelzoom** [comment]
Since this issue isn't specific to natural-selection, I'm transferring it to the studio repo.
